# Generated by Django 2.1.5 on 2019-10-17 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_series'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Series',
            new_name='Serie',
        ),
    ]
