# Generated by Django 2.1.5 on 2019-10-17 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20191016_1751'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Serie',
            new_name='Series',
        ),
        migrations.AlterModelOptions(
            name='series',
            options={'verbose_name_plural': 'Series'},
        ),
    ]
